export const DESTINATION_ACCOUNT_ALREADY_EXISTS =
  'DESTINATION_ACCOUNT_ALREADY_EXISTS'
export const DESTINATION_ACCOUNT_NOT_EXISTS = 'DESTINATION_ACCOUNT_NOT_EXISTS'
export const ORIGIN_ACCOUNT_NOT_EXISTS = 'ORIGIN_ACCOUNT_NOT_EXISTS'
export const EVENT_NOT_SUPPORTED = 'EVENT_NOT_SUPPORTED'